baseURL = 'https://cv.tormakristof.eu/'
languageCode = 'en-us'
title = 'Kristof Torma'
enableRobotsTXT = true
theme = "simple-resume"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]
